kind = "mobile"
previewPath = "/"
title = "مدير الملفات"
version = "1.0.0"
id = "artifacts/file-manager"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 24795

[services.development]
run = "pnpm --filter @workspace/file-manager run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/file-manager", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/file-manager", "run", "serve" ]

[services.env]
PORT = "24795"
BASE_PATH = "/"
